# Generated by Django 5.2.10 on 2026-01-22 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='source',
            field=models.CharField(choices=[('bcm', 'API Banque Centrale Mauritanie'), ('api', 'API Externe'), ('sim', 'Simulation'), ('init', 'Données Initiales')], default='api', help_text='Source de la donnée de prix', max_length=20),
        ),
        migrations.AddField(
            model_name='price',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
